{
 "title": "Full Stack Observability",
 "refresh": "5s",
 "panels": [
  {
   "title": "Backend CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total[1m]) * 100",
     "legendFormat": "CPU Usage %"
    }
   ]
  },
  {
   "title": "Backend Memory Usage (Heap Used)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes",
     "legendFormat": "{{space}}"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{route!=\"/metrics\"}[1m])) by (method, route) * 60",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Log Volume by Level (Summary)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({job=\"docker\"} | json | url != \"/metrics\" | url != \"\" [1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Error / Warning Logs Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "logs/s" } },
   "targets": [
    {
     "expr": "sum by (level) (rate({job=\"docker\"} | json | level=~\"error|warn\" [1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Live Backend Logs Stream",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{job=\"docker\"} | json | url != \"/metrics\" | url != \"\""
    }
   ]
  }
 ]
}